services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
