spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/tododb
    username: ${DB_USER:todo}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: false

resilience4j:
  circuitbreaker:
    instances:
      jsonPlaceholder:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

retry:
  instances:
    jsonPlaceholder:
      max-attempts: 3
      wait-duration: 2s
